###Create Show
POST http://localhost:3000/shows.json
Content-Type: application/json

{
  "title" : "A show",
  "plot" : "The things that happen",
  "year" : "0001"
}

###Update Show
PATCH http://localhost:3000/shows/1.json
Content-Type: application/json

{
  "year" : "2001"
}

###Destroy Show
DELETE http://localhost:3000/shows/8
Content-Type: application/json
